-- Evidence Fitness, Experimental Validity, Scope of Generalization.
--
-- 1. New enums.
-- 2. New columns (added first so the backfills below can use them).
-- 3. Backfill Evidence.sourceType from the legacy EvidenceType (and the
--    experiment type for experiment results).
-- 4. ClaimType: swap to the normalized taxonomy, mapping every existing link
--    (generic node / causal-link claims take the type of their level).
-- 5. EpistemicStatus: retire PROVEN. Rows are migrated to OBSERVED when a
--    supporting measurement-family source is linked, otherwise to
--    STRONGLY_SUPPORTED. KnowledgeChange JSON (the audit trail) is untouched.

-- CreateEnum
CREATE TYPE "EvidenceSourceType" AS ENUM ('INTERVIEW', 'SURVEY', 'CUSTOMER_QUOTE', 'FORUM_POST', 'REDDIT_POST', 'SALES_CONVERSATION', 'OBSERVED_WORKFLOW', 'PRODUCT_USAGE', 'CLICKSTREAM', 'PURCHASE_BEHAVIOR', 'CRM_DATA', 'TRANSACTION_RECORDS', 'FINANCIAL_RECORDS', 'SYSTEM_LOGS', 'BOOKING_DATA', 'POS_DATA', 'ERP_DATA', 'SUPPORT_TICKETS', 'TIME_TRACKING_DATA', 'COMPETITOR_REVIEW', 'PRICING_PAGE', 'JOB_POSTING', 'PUBLIC_FINANCIALS', 'INDUSTRY_REPORT', 'GOVERNMENT_DATA', 'MARKET_DATASET', 'PROTOTYPE_TEST', 'CONCIERGE_TEST', 'BEFORE_AFTER_TEST', 'MATCHED_COMPARISON', 'CONTROLLED_EXPERIMENT', 'AB_TEST', 'RANDOMIZED_EXPERIMENT', 'PRICING_EXPERIMENT', 'LANDING_PAGE_EXPERIMENT', 'TECHNICAL_SPIKE', 'BENCHMARK', 'DATA_FEASIBILITY_STUDY', 'INTEGRATION_TEST', 'LOAD_TEST', 'SIGNED_LOI', 'PAID_PILOT', 'CONTRACT', 'INVOICE', 'SUBSCRIPTION_PURCHASE', 'RENEWAL', 'EXPANSION', 'OTHER');

-- CreateEnum
CREATE TYPE "EvidenceAdmissibility" AS ENUM ('HIGH', 'MEDIUM', 'LOW', 'NOT_ADMISSIBLE');

-- CreateEnum
CREATE TYPE "ExperimentDesignLevel" AS ENUM ('ANECDOTAL', 'OBSERVATIONAL', 'BEFORE_AFTER', 'MATCHED_COMPARISON', 'CONTROLLED', 'RANDOMIZED');

-- CreateEnum
CREATE TYPE "InternalValidity" AS ENUM ('HIGH', 'MEDIUM', 'LOW', 'INDETERMINATE');

-- CreateEnum
CREATE TYPE "AssignmentMethod" AS ENUM ('NONE', 'SELF_SELECTED', 'CONVENIENCE', 'MATCHED', 'RANDOM');

-- CreateEnum
CREATE TYPE "GeneralizationStatus" AS ENUM ('UNTESTED', 'CASE_ONLY', 'SAMPLE_SUPPORTED', 'SEGMENT_SUPPORTED', 'BROADER_HYPOTHESIS', 'CONTRADICTED_ACROSS_CONTEXTS');

-- AlterTable
ALTER TABLE "CausalLink" ADD COLUMN     "claimScope" JSONB,
ADD COLUMN     "generalization" "GeneralizationStatus" NOT NULL DEFAULT 'UNTESTED',
ADD COLUMN     "inference" TEXT,
ADD COLUMN     "observedScope" JSONB;

-- AlterTable
ALTER TABLE "Evidence" ADD COLUMN     "organizationCount" INTEGER,
ADD COLUMN     "scope" JSONB,
ADD COLUMN     "sourceOriginId" TEXT,
ADD COLUMN     "sourceType" "EvidenceSourceType" NOT NULL DEFAULT 'OTHER',
ADD COLUMN     "userCount" INTEGER;

-- AlterTable
ALTER TABLE "EvidenceClaimLink" ADD COLUMN     "admissibility" "EvidenceAdmissibility",
ADD COLUMN     "fitBreakdown" JSONB,
ADD COLUMN     "fitComputedAt" TIMESTAMP(3),
ADD COLUMN     "fitScore" INTEGER,
ADD COLUMN     "fitVersion" TEXT;

-- AlterTable
ALTER TABLE "Experiment" ADD COLUMN     "designLevel" "ExperimentDesignLevel",
ADD COLUMN     "scope" JSONB,
ADD COLUMN     "validityPlan" JSONB;

-- AlterTable
ALTER TABLE "ExperimentResult" ADD COLUMN     "designLevel" "ExperimentDesignLevel",
ADD COLUMN     "internalValidity" "InternalValidity",
ADD COLUMN     "interpretation" TEXT,
ADD COLUMN     "organizationCount" INTEGER,
ADD COLUMN     "scope" JSONB,
ADD COLUMN     "userCount" INTEGER,
ADD COLUMN     "validityAssessment" JSONB,
ADD COLUMN     "validityInputs" JSONB;

-- AlterTable
ALTER TABLE "Opportunity" ADD COLUMN     "claimScope" JSONB;

-- AlterTable
ALTER TABLE "ValueChainNode" ADD COLUMN     "claimScope" JSONB,
ADD COLUMN     "generalization" "GeneralizationStatus" NOT NULL DEFAULT 'UNTESTED',
ADD COLUMN     "inference" TEXT,
ADD COLUMN     "observedScope" JSONB;

-- Backfill: legacy evidence type → source type (same rule as evidence-sources.ts).
UPDATE "Evidence" SET "sourceType" = (CASE "type"::text
  WHEN 'INTERVIEW' THEN 'INTERVIEW'
  WHEN 'SURVEY' THEN 'SURVEY'
  WHEN 'CUSTOMER_QUOTE' THEN 'CUSTOMER_QUOTE'
  WHEN 'FORUM_POST' THEN 'FORUM_POST'
  WHEN 'REDDIT' THEN 'REDDIT_POST'
  WHEN 'REVIEW' THEN 'COMPETITOR_REVIEW'
  WHEN 'COMPETITOR_REVIEW' THEN 'COMPETITOR_REVIEW'
  WHEN 'JOB_POSTING' THEN 'JOB_POSTING'
  WHEN 'SEARCH_SIGNAL' THEN 'MARKET_DATASET'
  WHEN 'MARKET_REPORT' THEN 'INDUSTRY_REPORT'
  ELSE 'OTHER' END)::"EvidenceSourceType"
WHERE "type"::text <> 'EXPERIMENT';

UPDATE "Evidence" e SET "sourceType" = (CASE x."experimentType"::text
  WHEN 'CUSTOMER_INTERVIEW' THEN 'INTERVIEW'
  WHEN 'PRICING_TEST' THEN 'PRICING_EXPERIMENT'
  WHEN 'LANDING_PAGE_TEST' THEN 'LANDING_PAGE_EXPERIMENT'
  WHEN 'CONCIERGE_TEST' THEN 'CONCIERGE_TEST'
  WHEN 'PROTOTYPE_TEST' THEN 'PROTOTYPE_TEST'
  WHEN 'DATA_FEASIBILITY_TEST' THEN 'DATA_FEASIBILITY_STUDY'
  WHEN 'AB_TEST' THEN 'AB_TEST'
  WHEN 'MANUAL_WORKFLOW_TEST' THEN 'CONCIERGE_TEST'
  WHEN 'COHORT_OBSERVATION' THEN 'OBSERVED_WORKFLOW'
  WHEN 'TECHNICAL_SPIKE' THEN 'TECHNICAL_SPIKE'
  WHEN 'RETROSPECTIVE_DATA_ANALYSIS' THEN 'TRANSACTION_RECORDS'
  ELSE 'OTHER' END)::"EvidenceSourceType"
FROM "Experiment" x
WHERE e."experimentId" = x.id AND e."type"::text = 'EXPERIMENT';

-- ClaimType: normalized taxonomy. Map every existing link before swapping the enum.
ALTER TABLE "EvidenceClaimLink" ADD COLUMN "claimType_next" TEXT;
UPDATE "EvidenceClaimLink" SET "claimType_next" = (CASE "claimType"::text
  WHEN 'ICP' THEN 'ICP_EXISTS'
  WHEN 'VARIABLE' THEN 'VARIABLE_IMPORTANCE'
  WHEN 'CURRENT_STATE' THEN 'CURRENT_STATE'
  WHEN 'PAIN' THEN 'PAIN_EXISTS'
  WHEN 'MAGNITUDE' THEN 'MAGNITUDE'
  WHEN 'FREQUENCY' THEN 'PAIN_FREQUENCY'
  WHEN 'ECONOMIC_IMPACT' THEN 'ECONOMIC_IMPACT'
  WHEN 'MECHANISM' THEN 'MECHANISM_FEASIBLE'
  WHEN 'WILLINGNESS_TO_PAY' THEN 'WILLINGNESS_TO_PAY'
  WHEN 'ALTERNATIVE' THEN 'ALTERNATIVE_EXISTS'
  WHEN 'TRIGGER' THEN 'TRIGGER_EXISTS'
  ELSE 'OTHER' END);
UPDATE "EvidenceClaimLink" l SET "claimType_next" = (CASE n."level"::text
  WHEN 'MECHANISM' THEN 'MECHANISM_FEASIBLE'
  WHEN 'CAPABILITY' THEN 'CAPABILITY_EXISTS'
  WHEN 'TRANSFORMATION' THEN 'TRANSFORMATION_OCCURS'
  WHEN 'OPERATIONAL_VALUE' THEN 'OPERATIONAL_VALUE'
  WHEN 'ECONOMIC_VALUE' THEN 'ECONOMIC_VALUE'
  WHEN 'STRATEGIC_OUTCOME' THEN 'STRATEGIC_OUTCOME'
  WHEN 'BUSINESS_OUTCOME' THEN 'BUSINESS_OUTCOME'
  ELSE 'OTHER' END)
FROM "ValueChainNode" n
WHERE l."valueChainNodeId" = n.id AND l."claimType"::text = 'VALUE_CHAIN_NODE';
UPDATE "EvidenceClaimLink" l SET "claimType_next" = (CASE f."level"::text || '>' || t."level"::text
  WHEN 'MECHANISM>CAPABILITY' THEN 'MECHANISM_CAUSES_CAPABILITY'
  WHEN 'CAPABILITY>TRANSFORMATION' THEN 'CAPABILITY_CAUSES_TRANSFORMATION'
  WHEN 'TRANSFORMATION>OPERATIONAL_VALUE' THEN 'TRANSFORMATION_CAUSES_OPERATIONAL_VALUE'
  WHEN 'OPERATIONAL_VALUE>ECONOMIC_VALUE' THEN 'OPERATIONAL_VALUE_CAUSES_ECONOMIC_VALUE'
  WHEN 'ECONOMIC_VALUE>STRATEGIC_OUTCOME' THEN 'ECONOMIC_VALUE_CAUSES_STRATEGIC_OUTCOME'
  WHEN 'STRATEGIC_OUTCOME>BUSINESS_OUTCOME' THEN 'STRATEGIC_OUTCOME_CAUSES_BUSINESS_OUTCOME'
  ELSE 'CAUSAL_EFFECT' END)
FROM "CausalLink" c
JOIN "ValueChainNode" f ON f.id = c."fromNodeId"
JOIN "ValueChainNode" t ON t.id = c."toNodeId"
WHERE l."causalLinkId" = c.id AND l."claimType"::text = 'CAUSAL_LINK';

-- AlterEnum
BEGIN;
CREATE TYPE "ClaimType_new" AS ENUM ('MARKET_EXISTS', 'ICP_EXISTS', 'ICP_ACCESSIBLE', 'PAIN_EXISTS', 'PAIN_SEVERITY', 'PAIN_FREQUENCY', 'CURRENT_STATE', 'TRIGGER_EXISTS', 'ALTERNATIVE_EXISTS', 'VARIABLE_IMPORTANCE', 'MAGNITUDE', 'POPULATION_AFFECTED', 'ECONOMIC_IMPACT', 'OPERATIONAL_VALUE', 'ECONOMIC_VALUE', 'STRATEGIC_OUTCOME', 'BUSINESS_OUTCOME', 'MECHANISM_FEASIBLE', 'CAPABILITY_EXISTS', 'TRANSFORMATION_OCCURS', 'MECHANISM_CAUSES_CAPABILITY', 'CAPABILITY_CAUSES_TRANSFORMATION', 'TRANSFORMATION_CAUSES_OPERATIONAL_VALUE', 'OPERATIONAL_VALUE_CAUSES_ECONOMIC_VALUE', 'ECONOMIC_VALUE_CAUSES_STRATEGIC_OUTCOME', 'STRATEGIC_OUTCOME_CAUSES_BUSINESS_OUTCOME', 'CAUSAL_EFFECT', 'EXISTING_SPEND', 'PURCHASE_INTENT', 'WILLINGNESS_TO_PAY', 'PRICE_ACCEPTANCE', 'ACTUAL_PURCHASE', 'RETENTION_INTENT', 'ACTUAL_RETENTION', 'BUYER_REACHABILITY', 'CHANNEL_ACCESS', 'PROCUREMENT_FEASIBILITY', 'OTHER');
ALTER TABLE "EvidenceClaimLink" ALTER COLUMN "claimType" TYPE "ClaimType_new" USING ("claimType_next"::"ClaimType_new");
ALTER TYPE "ClaimType" RENAME TO "ClaimType_old";
ALTER TYPE "ClaimType_new" RENAME TO "ClaimType";
DROP TYPE "public"."ClaimType_old";
COMMIT;
ALTER TABLE "EvidenceClaimLink" DROP COLUMN "claimType_next";

-- EpistemicStatus: retire PROVEN (audit JSON in KnowledgeChange is preserved as-is).
ALTER TABLE "ValueChainNode" ADD COLUMN "status_next" TEXT;
ALTER TABLE "CausalLink" ADD COLUMN "status_next" TEXT;
ALTER TABLE "ValuePath" ADD COLUMN "status_next" TEXT;
ALTER TABLE "Variable" ADD COLUMN "evidenceStatus_next" TEXT;

UPDATE "ValueChainNode" n SET "status_next" = CASE
  WHEN n."status"::text <> 'PROVEN' THEN n."status"::text
  WHEN EXISTS (
    SELECT 1 FROM "EvidenceClaimLink" l JOIN "Evidence" e ON e.id = l."evidenceId"
    WHERE l."valueChainNodeId" = n.id AND l."direction" = 'SUPPORTS'
      AND e."sourceType"::text IN ('OBSERVED_WORKFLOW','PRODUCT_USAGE','CLICKSTREAM','PURCHASE_BEHAVIOR','CRM_DATA','TRANSACTION_RECORDS','FINANCIAL_RECORDS','SYSTEM_LOGS','BOOKING_DATA','POS_DATA','ERP_DATA','SUPPORT_TICKETS','TIME_TRACKING_DATA','PROTOTYPE_TEST','CONCIERGE_TEST','BEFORE_AFTER_TEST','MATCHED_COMPARISON','CONTROLLED_EXPERIMENT','AB_TEST','RANDOMIZED_EXPERIMENT','PRICING_EXPERIMENT','LANDING_PAGE_EXPERIMENT','TECHNICAL_SPIKE','BENCHMARK','DATA_FEASIBILITY_STUDY','INTEGRATION_TEST','LOAD_TEST','SIGNED_LOI','PAID_PILOT','CONTRACT','INVOICE','SUBSCRIPTION_PURCHASE','RENEWAL','EXPANSION')
  ) THEN 'OBSERVED'
  ELSE 'STRONGLY_SUPPORTED' END;
UPDATE "CausalLink" c SET "status_next" = CASE
  WHEN c."status"::text <> 'PROVEN' THEN c."status"::text
  WHEN EXISTS (
    SELECT 1 FROM "EvidenceClaimLink" l JOIN "Evidence" e ON e.id = l."evidenceId"
    WHERE l."causalLinkId" = c.id AND l."direction" = 'SUPPORTS'
      AND e."sourceType"::text IN ('OBSERVED_WORKFLOW','PRODUCT_USAGE','CLICKSTREAM','PURCHASE_BEHAVIOR','CRM_DATA','TRANSACTION_RECORDS','FINANCIAL_RECORDS','SYSTEM_LOGS','BOOKING_DATA','POS_DATA','ERP_DATA','SUPPORT_TICKETS','TIME_TRACKING_DATA','PROTOTYPE_TEST','CONCIERGE_TEST','BEFORE_AFTER_TEST','MATCHED_COMPARISON','CONTROLLED_EXPERIMENT','AB_TEST','RANDOMIZED_EXPERIMENT','PRICING_EXPERIMENT','LANDING_PAGE_EXPERIMENT','TECHNICAL_SPIKE','BENCHMARK','DATA_FEASIBILITY_STUDY','INTEGRATION_TEST','LOAD_TEST','SIGNED_LOI','PAID_PILOT','CONTRACT','INVOICE','SUBSCRIPTION_PURCHASE','RENEWAL','EXPANSION')
  ) THEN 'OBSERVED'
  ELSE 'STRONGLY_SUPPORTED' END;
UPDATE "ValuePath" SET "status_next" = CASE WHEN "status"::text = 'PROVEN' THEN 'STRONGLY_SUPPORTED' ELSE "status"::text END;
UPDATE "Variable" SET "evidenceStatus_next" = CASE WHEN "evidenceStatus"::text = 'PROVEN' THEN 'STRONGLY_SUPPORTED' ELSE "evidenceStatus"::text END;

-- AlterEnum
BEGIN;
CREATE TYPE "EpistemicStatus_new" AS ENUM ('UNKNOWN', 'HYPOTHESIS', 'UNPROVEN', 'SUPPORTED', 'STRONGLY_SUPPORTED', 'OBSERVED', 'MIXED', 'CONTRADICTED');
ALTER TABLE "public"."CausalLink" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "public"."ValueChainNode" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "public"."ValuePath" ALTER COLUMN "status" DROP DEFAULT;
ALTER TABLE "public"."Variable" ALTER COLUMN "evidenceStatus" DROP DEFAULT;
ALTER TABLE "Variable" ALTER COLUMN "evidenceStatus" TYPE "EpistemicStatus_new" USING ("evidenceStatus_next"::"EpistemicStatus_new");
ALTER TABLE "ValueChainNode" ALTER COLUMN "status" TYPE "EpistemicStatus_new" USING ("status_next"::"EpistemicStatus_new");
ALTER TABLE "CausalLink" ALTER COLUMN "status" TYPE "EpistemicStatus_new" USING ("status_next"::"EpistemicStatus_new");
ALTER TABLE "ValuePath" ALTER COLUMN "status" TYPE "EpistemicStatus_new" USING ("status_next"::"EpistemicStatus_new");
ALTER TYPE "EpistemicStatus" RENAME TO "EpistemicStatus_old";
ALTER TYPE "EpistemicStatus_new" RENAME TO "EpistemicStatus";
DROP TYPE "public"."EpistemicStatus_old";
ALTER TABLE "CausalLink" ALTER COLUMN "status" SET DEFAULT 'HYPOTHESIS';
ALTER TABLE "ValueChainNode" ALTER COLUMN "status" SET DEFAULT 'HYPOTHESIS';
ALTER TABLE "ValuePath" ALTER COLUMN "status" SET DEFAULT 'UNKNOWN';
ALTER TABLE "Variable" ALTER COLUMN "evidenceStatus" SET DEFAULT 'UNKNOWN';
COMMIT;
ALTER TABLE "ValueChainNode" DROP COLUMN "status_next";
ALTER TABLE "CausalLink" DROP COLUMN "status_next";
ALTER TABLE "ValuePath" DROP COLUMN "status_next";
ALTER TABLE "Variable" DROP COLUMN "evidenceStatus_next";
